---
language: java
script: mvn -q install -P examples
jdk:
- openjdk7
matrix:
  include:
  - jdk: oraclejdk7
    script: mvn -q deploy --settings .travis-settings.xml -Dno.gem.deploy=true
  - jdk: oraclejdk7
    env: ANDROID_EXAMPLES=true
    language: android
    android:
      components:
        - build-tools-21.1.1
        - platform-tools
        - extra-android-support
        - android-21
        - android-15
        - sys-img-armeabi-v7a-android-15
    # Emulator Management: Create and start up in parallel with the install
    # An old emulator is used to use less resources
    before_install:
      - echo no | android create avd --force -n test -t android-15 --abi armeabi-v7a
      - emulator -avd test -no-skin -no-audio -no-window &
    # Build the Android example dependencies, without test, to install dependencies
    install: mvn verify -pl android,picocontainer -am -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    # Emulator Management: Wait until the emulator is ready
    before_script:
      - android-wait-for-emulator
    # Build and test the Android examples
    script: mvn verify -P android-examples -pl examples/android,examples/android/android-test -am -amd -Dandroid.device=test
  - jdk: oraclejdk8
    script: mvn -q deploy -P java8 -pl java8 --settings .travis-settings.xml -Dno.gem.deploy=true

branches:
  only:
  - master
notifications:
  email:
  - cukes-devs@googlegroups.com
  irc:
  - irc.freenode.org#cucumber
env:
  global:
  - secure: |-
      rEtPzPG3bMKzx00AwDJq5tsp8LSCds5ePV6ZP+wgECP2BVIoD16zP8F6T0fY
      QK/2etRW6pcernOGP8S3SQE4e5ZBT5sqYY0mhKlq2aiem3i3gAwEzZvdLjWV
      1C6KyQplzdjKdaYWOre8YSXv5vxS3ZVS6NJc+0EQM3olTKV3flQ=
  - secure: |-
      BEsHVhETHrO8vR/7huN3MUMQQKZycZgJ+sWszwQPnwaGJEm6ptssJn/LsiUJ
      K/qQhjdpmPiKZIoTruG4E3vc+adT/B2VcHD0897jNeUBoDd7Vj4vzOH6ePID
      969vCnA+6hpQuIM02R+4OJIBPXVtr1Ix/ye+KxS69cJ5N8QyTfY=
