language: java
sudo: false

cache:
  directories:
    - "$HOME/.m2"

install:
  - mvn install -DskipTests=true -DskipITs=true -Darchetype.test.skip=true -Dmaven.javadoc.skip=true -B -V --toolchains .travis-toolchains.xml

jobs:
  include:
    # 1.1 Semver check
    - stage: test
      jdk: openjdk11
      script: mvn verify -Pcheck-semantic-version -DskipTests=true -DskipITs=true -Darchetype.test.skip=true --toolchains .travis-toolchains.xml
      env: CHECK_SEMANTIC_VERSION=true

    # 1.2 Tests
    - stage: test
      jdk: openjdk11
      script: mvn verify -P-spotless-apply --toolchains .travis-toolchains.xml
      env:
      - VERIFY=true
      - CUCUMBER_PUBLISH_TOKEN=trigger/build/with/publish/plugin

      # 1.3 Coverage
    - stage: test
      jdk: openjdk11
      script: mvn jacoco:prepare-agent verify jacoco:report coveralls:report --toolchains .travis-toolchains.xml
      env:
      - COVERAGE=true

    # 1.4 Javadoc
    - jdk: openjdk11
      env: JAVADOC=true
      script:
        - mvn javadoc:jar --toolchains .travis-toolchains.xml

branches:
  only:
    - main
    - v4.x.x
    - v5.x.x
    - v6.x.x
