name: Test Java

on:
  pull_request:
    branches:
      - '**'
  workflow_call:
  push:
    branches:
      - main
      - v4.x.x
      - v5.x.x
      - v6.x.x
      - v7.x.x
      - renovate/**

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        version: [ 17, 21 ]
    name: 'Build Java ${{ matrix.version }} - ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.version }}
          cache: 'maven'
      - name: Install dependencies
        run: ./mvnw install -Pinclude-extra-modules -DskipTests=true -DskipITs=true -D"archetype.test.skip=true" -D"maven.javadoc.skip=true" --batch-mode -D"style.color=always" --show-version
      - name: Test
        run: ./mvnw verify -Pinclude-extra-modules -D"style.color=always"
        env:
          CUCUMBER_PUBLISH_TOKEN: ${{ secrets.CUCUMBER_PUBLISH_TOKEN }}

  javadoc:
    name: 'Javadoc'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'maven'
      - name: Install dependencies
        run: ./mvnw install -DskipTests=true -DskipITs=true -Darchetype.test.skip=true -Dmaven.javadoc.skip=true --batch-mode -Dstyle.color=always --show-version
      - name: Javadoc
        run: ./mvnw javadoc:jar -Dstyle.color=always

  semver:
    name: 'Semver'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'maven'
      - name: Install dependencies
        run: ./mvnw install -DskipTests=true -DskipITs=true -Darchetype.test.skip=true -Dmaven.javadoc.skip=true --batch-mode -Dstyle.color=always --show-version
      - name: Test (Semver check)
        run: ./mvnw verify -Pcheck-semantic-version -DskipTests=true -DskipITs=true -Darchetype.test.skip=true -Dstyle.color=always
