name: Test Java
  
permissions: { }  

on:
  pull_request:
    branches:
      - '**'
  workflow_call:
  push:
    branches:
      - main
      - v4.x.x
      - v5.x.x
      - v6.x.x
      - v7.x.x
      - renovate/**

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        version: [ 17, 21 ]
    name: 'Build Java ${{ matrix.version }} - ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.version }}
          cache: 'maven'
      - name: Install dependencies
        run: mvn install -Pinclude-extra-modules -DskipTests=true -DskipITs=true -D"archetype.test.skip=true" -D"maven.javadoc.skip=true" --batch-mode -D"style.color=always" --show-version
      - name: Test
        run: mvn verify -Pinclude-extra-modules -D"style.color=always"

  javadoc:
    name: 'Javadoc'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Install dependencies
        run: mvn install -DskipTests=true -DskipITs=true -Darchetype.test.skip=true -Dmaven.javadoc.skip=true --batch-mode -Dstyle.color=always --show-version
      - name: Javadoc
        run: mvn javadoc:jar -Dstyle.color=always

  semver:
    name: 'Semver'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Install dependencies
        run: mvn install -DskipTests=true -DskipITs=true -Darchetype.test.skip=true -Dmaven.javadoc.skip=true --batch-mode -Dstyle.color=always --show-version
      - name: Test (Semver check)
        run: mvn verify -Pcheck-semantic-version -DskipTests=true -DskipITs=true -Darchetype.test.skip=true -Dstyle.color=always
